apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  labels:
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/part-of: ${{ values.name }}
  name: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ${{ values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ${{ values.name }}
    spec:
      containers:
        - image: ${{ values.appContainer }}
          resources: {}
          name: app-inference
          envFrom:
            - configMapRef:
                name: ${{ values.name }}-model-config
          env:
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ${{  values.crewAILLMAPIKeySecretName  }}
                  key: ${{  values.crewAILLMAPIKeySecretKey  }}
          ports:
            - containerPort: ${{ values.appPort }}
          securityContext:
            runAsNonRoot: true
