{% for t in values.tasks %}
${{ t.name }}:
  description: |-
    ${{ t.description }}
  expected_output: "${{ t.expected_output | default("Best possible answer.") }}"
  agent: "${{ t.agent }}"
{% endfor %}