tools:
{% if values.tools and values.tools.length > 0 -%}
{% for t in values.tools -%}
  - name: "${{ t.name }}"
    url: "${{ t.url }}"
    transport: "${{ t.transport }}"
    {% if t.bearerTokenEnvVarName %}bearerTokenEnvVarName: ${{ t.bearerTokenEnvVarName | dump }}{% endif %}
{% endfor -%}
{% else -%}
  []
{% endif -%}